### ISSUE TITLE
[Backend] Images couldn't be uploaded in post editor

### ISSUE THREAD

**Issue by an920107** [an920107/health-care-website#80]
- As the title.
- ~~The reason hasn't been clarified yet.~~
  > Addressed in [comment](https://github.com/an920107/health-care-website/issues/80#issuecomment-2327822090)

**Comment by an920107** [comment]
It seems like to be related with #78 .

**Comment by Xunhaoz** [comment]
Bug was fixed.
It happened because of error storing path.
