### ISSUE TITLE
[Backend] Carousels response 500

### ISSUE THREAD

**Issue by an920107** [an920107/health-care-website#83]
## Description

- As the title.

## Screenshots

![截圖 2024-09-06 中午12 30 02](https://github.com/user-attachments/assets/ef57543d-1178-455a-bfed-02cfc3ee019f)

**Comment by Xunhaoz** [comment]
Carousels was deleted accidentally.

![image](https://github.com/user-attachments/assets/5556a38e-3632-46cc-97ee-2182d6fedcab)
