### ISSUE TITLE
[Frontend] Dengue table get error inspection_time

### ISSUE THREAD

**Issue by Xunhaoz** [an920107/health-care-website#91]
### fill content
![image](https://github.com/user-attachments/assets/0b9cd9e1-5bfa-4d8f-8793-f564a6eb12ea)

**Comment by Xunhaoz** [comment]
### got content
![image](https://github.com/user-attachments/assets/9a647e35-5ff3-4dfe-89a8-d31dfd8430bb)

**Comment by an920107** [comment]
Addressed in d433e770ef343461c8358d68fadb051c27746202.
